apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: project-demo
  annotations:
    github.com/project-slug: naveen787-github/project-demo
spec:
  type: other
  lifecycle: unknown
  owner: guests
